[package]
name = "asciidoc-rs"
version = "0.1.0"
authors = ["Xargin <cao1988228@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.0"
pest_derive = "2.0"
serde_json = "1.0.37"
